#ifndef CONSTANTS_H
#define CONSTANTS_H

#define WINDOW_WIDTH 1300
#define WINDOW_HEIGHT 730
#define BORDER_WIDTH 400 
#define BORDER_HEIGHT 200

#define FISH_WIDTH 18
#define FISH_HEIGHT 12
#define FISH_NUMBER 500
#define LEADER_NUMBER 55

#define TURNFACTOR 0.4 

#define NOISE_FACTOR 30

#define ADVOID_FACTOR 0.5 
#define MATCHING_FACTOR 0.5 
#define CENTER_FACTOR 0.05 

#define PROTECT_RADIUS 25 
#define VISUAL_RADIUS 150

#define MIN_SPEED 120
#define MAX_SPEED 150 

#define DT 0.03

#define LEADER_FACTOR 0.5
#define TARGET_RADIUS 300 
#define TARGET_SPEED 0.025

#endif
